- hosts: depl
  tasks:
     - name: Copy using inline content
       become: yes
       become_user: root    
       blockinfile:
         path: /opt/splunk/etc/system/local/server.conf
         block: |
            [shclustering]
            pass4SymmKey = 12345678
            shcluster_label = cluster1

     - name: restart
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk restart
