- hosts: deployer
  tasks:

     - name: Downloading splunk
       get_url:
          url: https://download.splunk.com/products/splunk/releases/8.1.3/linux/splunk-8.1.3-63079c59e632-Linux-x86_64.tgz
          dest: /home/ec2-user
          mode: '0755'

     - name: archive file
       become: yes
       become_user: root
       ansible.builtin.unarchive:
          src: /home/ec2-user/splunk-8.1.3-63079c59e632-Linux-x86_64.tgz
          dest: /opt
          remote_src: yes
      
     - name: start splunk with accept license
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt

     - name: To set admin and password for login
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk cmd splunkd rest --noauth POST /services/authentication/users "name=admin&password=shubham123&roles=admin"

     - name: splunk restart for save password properly
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk restart

     - name: boot start to set root user
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk enable boot-start -user root
 
     - name: splunk restart (last stage)
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk restart
