- hosts: depl
  tasks:
     - name: Copy using inline content
       become: yes
       become_user: root
       ansible.builtin.copy:
          content: 
              [shclustering]
          dest: /opt/splunk/etc/system/local/server.conf
