#add file to deployer


#creating search head cluster

- hosts: shcluster1
  tasks:
     - name: search head 1
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk init shcluster-config -auth admin:shubham123 -mgmt_uri https://65.1.111.213:8089 -replication_port 9000 -replication_factor 3 -conf_deploy_fetch_url http://13.235.80.78:8089 -secret $7$osOdUZ1uf0OEyi8N/QqRHxibddHV6hGklEcnolniG+jwLA8FYobSQqY= -shcluster_label cluster1

     - name: restart
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk restart


- hosts: shcluster2
  tasks:
     - name: shcluster2
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk init shcluster-config -auth admin:shubham123 -mgmt_uri https://65.0.109.127:8089 -replication_port 9000 -replication_factor 3 -conf_deploy_fetch_url http://13.235.80.78:8089 -secret $7$osOdUZ1uf0OEyi8N/QqRHxibddHV6hGklEcnolniG+jwLA8FYobSQqY= -shcluster_label cluster1
   
     - name: restart
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk restart


- hosts: shcluster3
  tasks:
     - name: shcluster3
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk init shcluster-config -auth admin:shubham123 -mgmt_uri https://3.110.124.204:8089 -replication_port 9000 -replication_factor 2 -conf_deploy_fetch_url http://13.235.80.78:8089 -secret $7$osOdUZ1uf0OEyi8N/QqRHxibddHV6hGklEcnolniG+jwLA8FYobSQqY= -shcluster_label cluster1

     - name: restart
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk restart

     - name: configuration of index cluster and search head cluster
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk bootstrap shcluster-captain -servers_list "https://65.1.111.213:8089,https://65.0.109.127:8089,https://3.110.124.204:8089" -auth admin:shubham123


