- hosts: depl
  tasks:
     - name: Update hosts
       become: yes
       become_user: root
       lineinfile:
            path: /opt/splunk/etc/system/local/server.conf
            line: "{{ item }}"
       with_items:
       - [shclustering]
       - pass4SymmKey = 12345678
       - shcluster_label = cluster1
