- hosts: shcluster1
  tasks:
     - name: search head 1
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk init shcluster-config -auth admin:shubham123 -mgmt_uri https://65.1.111.213:8089 -replication_port 9000 -replication_factor 3 -conf_deploy_fetch_url http://13.235.80.78:8089 -secret $7$sOJb4+4Qf+nWzOuJW+OwzG0AEdi4cT42Z+dpm9KDg/cPB645dMi41g== -shcluster_label cluster1



- hosts: shcluster2
  tasks:
     - name: shcluster2
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk init shcluster-config -auth admin:shubham123 -mgmt_uri https://65.0.109.127:8089 -replication_port 9000 -replication_factor 3 -conf_deploy_fetch_url http://13.235.80.78:8089 -secret $7$sOJb4+4Qf+nWzOuJW+OwzG0AEdi4cT42Z+dpm9KDg/cPB645dMi41g== -shcluster_label cluster1


- hosts: shcluster3
  tasks:
     - name: shcluster3
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk init shcluster-config -auth admin:shubham123 -mgmt_uri https://3.110.124.204:8089 -replication_port 9000 -replication_factor 2 -conf_deploy_fetch_url http://13.235.80.78:8089 -secret $7$sOJb4+4Qf+nWzOuJW+OwzG0AEdi4cT42Z+dpm9KDg/cPB645dMi41g== -shcluster_label cluster1



