- hosts: depl
  tasks:
     - name: Copy using inline content
       become: yes
       become_user: root    
       copy:
       content: |
            - [shclustering]
            - pass4SymmKey = yoursecuritykey
            - shcluster_label = shcluster1
       dest: /opt/splunk/etc/system/local/server.conf
