#add file to deployer
- hosts: depl
  tasks:
     - name: Copy using inline content
       become: yes
       become_user: root    
       copy:
         dest: /opt/splunk/etc/system/local/server.conf
         content: |
            [shclustering]
            pass4SymmKey = shubham123
            shcluster_label = cluster1

     - name: restart
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk restart

#creating search head cluster

- hosts: shcluster1
  tasks:
     - name: search head 1
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk init shcluster-config -auth admin:shubham123 -mgmt_uri https://65.1.111.213:8089 -replication_port 9000 -replication_factor 3 -conf_deploy_fetch_url http://13.235.80.78:8089 -secret $7$qMGvUwmRmuC4awZ67C22tvV8HmnF1K9/MOL+QgLrGk3faXZuU0OzUgET -shcluster_label cluster1




- hosts: shcluster2
  tasks:
     - name: shcluster2
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk init shcluster-config -auth admin:shubham123 -mgmt_uri https://65.0.109.127:8089 -replication_port 9000 -replication_factor 3 -conf_deploy_fetch_url http://13.235.80.78:8089 -secret $7$qMGvUwmRmuC4awZ67C22tvV8HmnF1K9/MOL+QgLrGk3faXZuU0OzUgET -shcluster_label cluster1



- hosts: shcluster3
  tasks:
     - name: shcluster3
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk init shcluster-config -auth admin:shubham123 -mgmt_uri https://3.110.124.204:8089 -replication_port 9000 -replication_factor 2 -conf_deploy_fetch_url http://13.235.80.78:8089 -secret $7$qMGvUwmRmuC4awZ67C22tvV8HmnF1K9/MOL+QgLrGk3faXZuU0OzUgET -shcluster_label cluster1



     - name: configuration of index cluster and search head cluster
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk bootstrap shcluster-captain -servers_list "https://65.1.111.213:8089,https://65.0.109.127:8089,https://3.110.124.204:8089" -auth admin:shubham123

#configuration of index clustering and search-head clustering

- hosts: shcluster1
  tasks:
     - name: search head 1
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk edit cluster-config -mode searchhead -master_uri https://13.126.84.98:8089 -secret $7$qMGvUwmRmuC4awZ67C22tvV8HmnF1K9/MOL+QgLrGk3faXZuU0OzUgET

- hosts: shcluster2
  tasks:
     - name: search head 2
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk edit cluster-config -mode searchhead -master_uri https://13.126.84.98:8089 -secret $7$qMGvUwmRmuC4awZ67C22tvV8HmnF1K9/MOL+QgLrGk3faXZuU0OzUgET

- hosts: shcluster3
  tasks:
     - name: search head 3
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk edit cluster-config -mode searchhead -master_uri https://13.126.84.98:8089 -secret $7$qMGvUwmRmuC4awZ67C22tvV8HmnF1K9/MOL+QgLrGk3faXZuU0OzUgET

         
       
   
