- hosts: deployer1
  tasks:
     - name: splunk restart for save password properly
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk edit cluster-config -mode peer -manager_uri https://13.233.104.188:8089 -replication_port 8085 -secret 12345678
