
- name: Ansible test
  hosts: localhost
  connection: local
  tasks:
    - name: launching AWS instance using Ansible
      ec2:
         key_name: ansible
         instance_type: t2.micro
         image: ami-01a4f99c4ac11b03c
         region: ap-south-1
         wait: yes
         count: 1
         vpc_subnet_id: subnet-0bc136f7fca55cae6
         assign_public_ip: yes
         aws_access_key: AKIAVC7WKC64WGN3IQPW
         aws_secret_key: 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
